#!/usr/bin/python3
#
# Run the machine emulator and bootstrap into the "Program Input Routine".
#
# Usage: lgp21-run

import sys
import lgp21.machine as machine

with machine.Machine() as mach:
    if len(sys.argv) > 1 and sys.argv[1] == "-v":
        mach.verbose = True
    mach.bootstrap()
    while True:
        # Run the machine until it halts.
        mach.run()

        # Reset and jump back into the "Program Input Routine".
        mach.A = 0
        mach.C = 0
        mach.overflow = False
        mach.resume()
